tap "aws/tap"
tap "borkdude/brew"
tap "clojure-lsp/brew"
tap "clojure/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "microsoft/git"
tap "reviewdog/tap"
tap "saulpw/vd"
tap "xo/xo"
brew "adr-tools"
brew "asciinema"
brew "aws-vault"
brew "awscli"
brew "bat"
brew "bottom"
brew "caddy"
brew "clojure"
brew "clojure-lsp/brew/clojure-lsp-native"
brew "difftastic"
brew "dog"
brew "dua-cli"
brew "exa"
brew "fd"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "hyperfine"
brew "jenv"
brew "jet"
brew "jq"
brew "mas"
brew "packer"
brew "pandoc"
brew "ripgrep"
brew "starship"
brew "terraform"
brew "terraform-docs"
brew "tflint"
brew "tldr"
brew "tokei"
brew "up"
brew "xh"
brew "zsh"
brew "saulpw/vd/visidata"
brew "vegeta"
brew "xo/xo/usql"
brew "zellij"
cask "alacritty"
cask "amazon-chime"
cask "authy"
cask "dash"
cask "docker"
cask "git-credential-manager-core"
cask "google-chrome"
cask "keycastr"
cask "logitech-options"
cask "lunar"
cask "numi"
cask "raycast"
cask "slack"
cask "sublime-text"
cask "sublime-merge"
cask "temurin"
cask "visual-studio-code"
cask "visualvm"
cask "whatsapp"
cask "zoom"
mas "AdGuard for Safari", id: 1440147259
mas "Browserism", id: 979047768
mas "Developer", id: 640199958
mas "DuckDuckGo Privacy for Safari", id: 1482920575
mas "Hush", id: 1544743900
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Vinegar", id: 1591303229
