tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "isen-ng/dotnet-sdk-versions"
tap "microsoft/git"
tap "aws/tap"
brew "act"
brew "actionlint"
brew "adr-tools"
brew "awscli"
brew "aws-sam-cli"
brew "bat"
brew "bottom"
brew "caddy"
brew "cloc"
brew "dog"
brew "dua-cli"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-quick-stats"
brew "glow"
brew "hyperfine"
brew "jenv"
brew "jq"
brew "macos-trash"
brew "mas"
brew "packer"
brew "ripgrep"
brew "starship"
brew "structurizr-cli"
brew "terraform"
brew "terraform-docs"
brew "tldr"
brew "tokei"
brew "up"
brew "volta"
brew "xh"
brew "zsh"
cask "amazon-chime"
cask "amazon-music"
cask "authy"
cask "aws-vault"
cask "bitwarden"
cask "cheatsheet"
cask "dash"
cask "docker"
cask "dotnet-sdk"
cask "font-fira-code"
cask "git-credential-manager-core"
cask "google-chrome"
cask "gotomeeting"
cask "jetbrains-toolbox"
cask "logitech-camera-settings"
cask "logitech-options"
cask "macs-fan-control"
cask "numi"
cask "racket"
cask "raycast"
cask "slack"
cask "temurin"
cask "visual-studio-code"
cask "visualvm"
cask "webex"
mas "AdGuard for Safari", id: 1440147259
mas "Browserism", id: 979047768
mas "Developer", id: 640199958
mas "Hush", id: 1544743900
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Vinegar", id: 1591303229
